---
# yaml format
all:
  children:
    routers:
      hosts:
        192.168.122.10
      vars:
        ansible_network_os: ios
        ansible_user: randy
        ansible_password: test
        ntp_server1: "192.0.2.1"
        ntp_server2: "192.0.2.2"
        loopback0: "1.1.1.1"
        loopback0_mask: "255.255.255.255"
        net_mask: "255.255.255.255"
        bgp_neighbor1: "192.168.122.11"
        bgp_neighbor2: "192.168.122.12"
        bgp_asn_1: "1"
        bgp_neighbor1_remote_as: "2"
        bgp_neighbor2_remote_as: "3"
    servers:
      hosts:
        192.168.122.11:
      vars:
        ansible_network_os: ios
        ansible_user: randy
        ansible_password: test
        ntp_server1: "192.0.2.1"
        ntp_server2: "192.0.2.2"
        loopback0: "2.2.2.2"
        loopback0_mask: "255.255.255.255"
        net_mask: "255.255.255.255"
        bgp_neighbor1: "192.168.122.10"
        bgp_neighbor2: "192.168.122.12"
        bgp_asn_1: 2
        bgp_neighbor1_remote_as: 1
        bgp_neighbor2_remote_as: 3
    switches:
      hosts:
        192.168.122.12:
      vars:
        ansible_network_os: ios
        ansible_user: randy
        ansible_password: test
        ntp_server1: "192.0.2.1"
        ntp_server2: "192.0.2.2"
        loopback0: "3.3.3.3"
        loopback0_mask: "255.255.255.255"
        net_mask: "255.255.255.255"
        bgp_neighbor1: "192.168.122.10"
        bgp_neighbor2: "192.168.122.11"
        bgp_asn_1: 3
        bgp_neighbor1_remote_as: 1
        bgp_neighbor2_remote_as: 2

