---
- name: "PLAY 1: Remove BGP config from Router 1"
  hosts: routers
  tasks:
    - name: "TASK 1: Log into routers and remove config"
      ios_config:
        lines:
          - "no router bgp {{ bgp_asn_1 }}"
          - "interface loopback0"
          - "no ip address"

      register: bgp_updates

    - name: "TASK 2: Print changes if they occur"
      debug:
        var: bgp_updates.commands
      when: "bgp_updates.commands is defined"


- name: "PLAY 2: Remove BGP config from Server"
  hosts: servers
  tasks:
    - name: "TASK 1: Log into routers and remove config"
      ios_config:
        lines:
          - "no router bgp {{ bgp_asn_1 }}"
          - "interface loopback0"
          - "no ip address"

      register: bgp_updates

    - name: "TASK 2: Print changes if they occur"
      debug:
        var: bgp_updates.commands
      when: "bgp_updates.commands is defined"


- name: "PLAY 3: Remove BGP config from Switch"
  hosts: switches
  tasks:
    - name: "TASK 1: Log into routers and remove config"
      ios_config:
        lines:
          - "no router bgp {{ bgp_asn_1 }}"
          - "interface loopback0"
          - "no ip address"

      register: bgp_updates

    - name: "TASK 2: Print changes if they occur"
      debug:
        var: bgp_updates.commands
      when: "bgp_updates.commands is defined"

